bind = '0.0.0.0:8888'
workers = 4
worker_class = 'uvicorn.workers.UvicornWorker'
# worker_connections = 1000
# timeout = 120
# keepalive = 5
preload_app = True
# max_requests = 1000
# max_requests_jitter = 100
accesslog = '-'
errorlog = '-'
loglevel = 'info'
limit_request_line = 4096